In [5]:
import numpy as np

In [1]:
##1 Homogeneity and heterogeneity. The list can contain the data of different types where as ndarray has same types. This helps in avoiding multiple loops while doing mathematical operations.

In [2]:
##2 dtypes define the type of data(int, float etc) inside the array, ie what kind of data is available there. This helps in fastening up calcualations as it knows the data type, also the memory optimisation is good as well.Data cleaning, changing dtypes etc are key features as well. There are many more features but I will not explain them right now.

In [3]:
##3 B np.zeros(5)

In [4]:
##4 The question is not correct

In [12]:
##5
arr = np.arange(12)
arr2 = arr.reshape(3,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
##6
print((np.arange(10))*10)

[ 0 10 20 30 40 50 60 70 80 90]


In [22]:
##7
arr = np.array([5, 10, 15, 20, 25])
arr[0:3]

array([ 5, 10, 15])

In [25]:
##8
data = np.array([7.5, 8.0, 9.0, 10.5])
print(data.sum())
print(data.mean())

35.0
8.75


In [26]:
##9
vals = np.array([3, 7, 2, 9, 1, 8])
print(vals[vals>5])

[7 9 8]


In [32]:
##10
arr = np.array([1, 2, 3, 4])
arr_float = arr.astype(float)
print(arr)
print(arr.dtype)
print(arr_float)
print(arr_float.dtype)

[1 2 3 4]
int64
[1. 2. 3. 4.]
float64
